[package]
name = "office-crypto-wasm"
version = "0.1.0"
authors = ["Kenta Kudo <yd37574@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.69"
office-crypto-rs = { path = "../office-crypto-core" }
wasm-bindgen = "0.2.92"
